/*
 * Decompiled with CFR 0.152.
 */
package dev.langchain4j.mcp.protocol;

public enum McpClientMethod {
    INITIALIZE,
    TOOLS_CALL,
    TOOLS_LIST,
    NOTIFICATION_CANCELLED,
    NOTIFICATION_INITIALIZED,
    PING,
    RESOURCES_LIST,
    RESOURCES_READ,
    RESOURCES_TEMPLATES_LIST,
    PROMPTS_LIST,
    PROMPTS_GET,
    NOTIFICATION_ROOTS_LIST_CHANGED,
    RESOURCES_SUBSCRIBE,
    RESOURCES_UNSUBSCRIBE;

}

